### ISSUE TITLE
Provide a multi arch Pipeline Build for the Starter Apps

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/devel-bucket#10]
It is now possible to import and create an OpenShift Pipeline by using the Developer View + wizard and referencing the repo

such as : https://github.com/cloud-native-robotz-hackathon/starter-app-python

Images built in this way will not work on the robot/arm due to the underlying architecture and pip commmands executed as part of the S2i build.

We need a way to build arm oder mulitarch images in the datacenter OpenShift cluster to deploy to the robots. 

Perhaps it is possible to reference a prebuilt arm base image, that has all the dependencies in S2i?

**Comment by rbo** [comment]
We can try to use my multi-arch cluster at hetzner:

```
$ oc get nodes -L kubernetes.io/arch
NAME                                STATUS   ROLES                  AGE     VERSION           ARCH
control-plane-0   Ready    control-plane,master   2d11h   v1.26.7+0ef5eae   arm64
worker-0-arm      Ready    worker                 114m    v1.26.7+0ef5eae   arm64
worker-0-x86      Ready    worker                 3h31m   v1.26.7+0ef5eae   amd64
```

**Comment by rbo** [comment]
https://github.com/openshift-examples/multi-arch/blob/main/.tekton/multi-arch.yaml

**Comment by rbo** [comment]
fixed in https://github.com/cloud-native-robotz-hackathon/starter-app-python/blob/master/.tekton/build.yaml

**Comment by rbo** [comment]
Images available at: https://quay.io/repository/cloud-native-robotz-hackathon/starter-app-python?tab=tags
