### ISSUE TITLE
Open Image Dataset nicht möglich nach Klassen zu suchen ohne Login

### ISSUE THREAD

**Issue by kblase** [cloud-native-robotz-hackathon/devel-bucket#14]
https://storage.googleapis.com/openimages/web/visualizer/index.html

**Comment by kblase** [comment]
![image](https://github.com/cloud-native-robotz-hackathon/devel-bucket/assets/53231329/2e2006c5-c9d7-447b-8b05-b4913b815789)

Nach klick auf detection Boxes geht es

**Comment by nexus-Six** [comment]
Genau. Man muss zuerst die Art der Visualization der Metadaten wählen.
