### ISSUE TITLE
Define and Test Hackathon Flow

### ISSUE THREAD

**Issue by nexus-Six** [cloud-native-robotz-hackathon/devel-bucket#8]
- Create GitOps Config Repos
- Test ARM Image for Starter App

**Comment by nexus-Six** [comment]
Multiarch test:
- Creating starter-app-python base image with pip requirements.txt on ARM
- Build new starter-app-python on x64 with ARM base image
- Started final image on x64 -> warning but works
- Started final image on ARM -> works

**Comment by goetzrieger** [comment]
Done:
- Gitea install
- Skupper connect public to local OCP, exposed as route
- starterapp-python in DevSpaces tested against route

ToDo:
- Pipeline: Create app from Gitea repo
- Pipeline: Push image to Quay
- GitOps: create config repo in Gitea, 
- GitOps: Setup RBAC to differentiate teams/robots/managed microshift clusters 
- GitOps : deploy to robot
- HubController : Trigger Starter App on Robot Microshift
